### PR TITLE
Adds CodePen job board

### PR DESCRIPTION
**Pull request by mlr**
CodePen launched [their job board](http://blog.codepen.io/2014/12/08/announcing-codepen-job-board/) today, added  it to the scraper with logo.

### CODE REVIEW

**Comment by scotthasbrouck** [comment]
Awesome - great find! IMHO job boards on sites like CodePen, Product Hunt, YC, etc, offer much better hacker jobs. For example, someone sent me the feedback today that some of these sites are scraping jobs at companies like Nordstrom. Not exactly a hacker job.

**Comment by mlr** [comment]
:+1: 

Hmm I did see a couple of the jobs from Nordstrom, apparently they're hiring software engineers too.  Was the feedback referring to non-engineering related jobs from them as well?

**Comment by scotthasbrouck** [comment]
Not so much non-engineering jobs. Just engineering jobs at old-world companies. I think it's spot on - hackersurf users wouldn't likely be interested in working for Nordstrom.

**Comment by mlr** [comment]
Ah right right, yeah I can understand that. It'd be cool if there were reddit style down-voting that auto-filtered old-guard/non-hacker companies like that.  I suppose a simpler implementation would be to just blacklist certain companies.

**Comment by scotthasbrouck** [comment]
I agree with both of those ideas. Back to a bigger picture view, over the weekend, I was thinking it would make more sense to see a uniform list from all sites, ordered by most recent / or by upvoting jobs. Companies that get upvoted job posts more will have more "karma" similar to HN.

**Comment by mlr** [comment]
Very cool, I agree. Instead of a header for each of the source sites it could just be a small label or the logo within the uniform list.

**Pull request merged**
